export const Namespaces = {
    HTTPBIND: "http://jabber.org/protocol/httpbind",
    BOSH: "urn:xmpp:xbosh",
    CLIENT: "jabber:client",
    AUTH: "jabber:iq:auth",
    ROSTER: "jabber:iq:roster",
    PROFILE: "jabber:iq:profile",
    DISCO_INFO: "http://jabber.org/protocol/disco#info",
    DISCO_ITEMS: "http://jabber.org/protocol/disco#items",
    MUC: "http://jabber.org/protocol/muc",
    SASL: "urn:ietf:params:xml:ns:xmpp-sasl",
    STREAM: "http://etherx.jabber.org/streams",
    FRAMING: "urn:ietf:params:xml:ns:xmpp-framing",
    BIND: "urn:ietf:params:xml:ns:xmpp-bind",
    SESSION: "urn:ietf:params:xml:ns:xmpp-session",
    VERSION: "jabber:iq:version",
    STANZAS: "urn:ietf:params:xml:ns:xmpp-stanzas",
    XHTML_IM: "http://jabber.org/protocol/xhtml-im",
    XHTML: "http://www.w3.org/1999/xhtml",
    // XMPP.Bookmarks
    PRIVATE: 'jabber:iq:private',
    BOOKMARKS: 'storage:bookmarks',
    PRIVACY: 'jabber:iq:privacy',
    DELAY: 'jabber:x:delay',
    PUBSUB: 'http://jabber.org/protocol/pubsub',
    // XMPP.Caps
    CAPS: 'http://jabber.org/protocol/caps',
    // XMPP.MAM
    MAM: 'urn:xmpp:mam:2',
    // XMPP.MUC
    MUC_OWNER: "http://jabber.org/protocol/muc#owner",
    MUC_ADMIN: "http://jabber.org/protocol/muc#admin",
    MUC_USER: "http://jabber.org/protocol/muc#user",
    MUC_ROOMCONF: "http://jabber.org/protocol/muc#roomconfig",
    MUC_REGISTER: "jabber:iq:register",
    // XMPP.Roster
    ROSTER_VER: 'urn:xmpp:features:rosterver',
    NICK: 'http://jabber.org/protocol/nick',
    // XMPP.RSM
    RSM: 'http://jabber.org/protocol/rsm',
    // VARIOUS
    DATA: 'jabber:x:data'
}